# GENERATED FILE! ONLY EDIT FOR TESTING!

from enum import Enum, unique


@unique
class FieldName(Enum):
    AC_I_P_TOTAL = "ac_i_p_total"
    AC_O_P_TOTAL = "ac_o_p_total"
    B_SOC_TOTAL = "b_soc_total"
    D_INVERTER_TYPE = "d_inverter_type"
    D_SERIAL = "d_serial"
    DC_I_P_TOTAL = "dc_i_p_total"
    DC_O_P_TOTAL = "dc_o_p_total"
    AC_O_SWITCH = "ac_o_switch"
    AC_POWER_LIFTING_SWITCH = "ac_power_lifting_switch"
    DC_O_SWITCH = "dc_o_switch"
    PV_I_E_TOTAL = "pv_i_e_total"
    D_TIME_REMAINING = "d_time_remaining"
    AC_1_I_V = "ac_1_i_v"
    AC_1_O_V = "ac_1_o_v"
    AC_ECO_MODE = "ac_eco_mode"
    AC_ECO_SWITCH = "ac_eco_switch"
    AC_I_F = "ac_i_f"
    AC_1_I_C = "ac_1_i_c"
    AC_O_F = "ac_o_f"
    B_VER_BMS = "b_ver_bms"
    D_CHARGING_MODE = "d_charging_mode"
    DC_ECO_MODE = "dc_eco_mode"
    DC_ECO_SWITCH = "dc_eco_switch"
    DC_I_C = "dc_i_c"
    DC_I_V = "dc_i_v"
    G_I_F = "g_i_f"
    AC_O_MODE = "ac_o_mode"
    AC_UPS_MODE = "ac_ups_mode"
    B_SOC_HIGH = "b_soc_high"
    B_SOC_LOW = "b_soc_low"
    D_DISPLAY_MODE = "d_display_mode"
    D_POWER_OFF = "d_power_off"
    D_VER_ARM = "d_ver_arm"
    D_VER_DSP = "d_ver_dsp"
    PV_1_I_C = "pv_1_i_c"
    PV_1_I_P = "pv_1_i_p"
    D_SPLIT_PHASE_SWITCH = "d_split_phase_switch"
    D_SPLIT_PHASE_MODE = "d_split_phase_mode"
    PV_1_I_V = "pv_1_i_v"
    D_LED_MODE = "d_led_mode"
    AC_1_O_C = "ac_1_o_c"
    AC_1_O_P = "ac_1_o_p"
    AC_2_O_C = "ac_2_o_c"
    AC_2_O_P = "ac_2_o_p"
    AC_2_O_V = "ac_2_o_v"
    AC_3_O_C = "ac_3_o_c"
    AC_3_O_P = "ac_3_o_p"
    AC_3_O_V = "ac_3_o_v"
    AC_1_I_P = "ac_1_i_p"
    AC_2_I_C = "ac_2_i_c"
    AC_2_I_P = "ac_2_i_p"
    AC_2_I_V = "ac_2_i_v"
    AC_3_I_C = "ac_3_i_c"
    AC_3_I_P = "ac_3_i_p"
    AC_3_I_V = "ac_3_i_v"
    B_TYPE = "b_type"
    PV_2_I_C = "pv_2_i_c"
    PV_2_I_P = "pv_2_i_p"
    PV_2_I_V = "pv_2_i_v"
    PV_3_I_C = "pv_3_i_c"
    PV_3_I_P = "pv_3_i_p"
    PV_3_I_V = "pv_3_i_v"
    PV_4_I_C = "pv_4_i_c"
    PV_4_I_P = "pv_4_i_p"
    PV_4_I_V = "pv_4_i_v"
    PV_5_I_C = "pv_5_i_c"
    PV_5_I_P = "pv_5_i_p"
    PV_5_I_V = "pv_5_i_v"
