from ..base_devices import BluettiDevice
from ..fields import *

# GENERATED FILE! ONLY EDIT FOR TESTING!


class AC200PL(BluettiDevice):
    def __init__(self):
        super().__init__(
            [
                UIntField(
                    FieldName.AC_1_O_V,
                    71,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_I_P_TOTAL,
                    37,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_O_F,
                    74,
                    unit="Hz",
                    sensor="frequency",
                ),
                EnumField(
                    FieldName.AC_O_MODE,
                    70,
                ),
                UIntField(
                    FieldName.AC_O_P_TOTAL,
                    38,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                BoolField(
                    FieldName.AC_O_SWITCH,
                    3007,
                ),
                UIntField(
                    FieldName.B_SOC_TOTAL,
                    43,
                    unit="%",
                    sensor="battery",
                    state_type="measurement",
                ),
                EnumField(
                    FieldName.D_DISPLAY_MODE,
                    3061,
                ),
                StringField(
                    FieldName.D_INVERTER_TYPE,
                    10,
                ),
                BoolField(
                    FieldName.D_POWER_OFF,
                    3060,
                ),
                SerialNumberField(
                    FieldName.D_SERIAL,
                    17,
                ),
                UIntField(
                    FieldName.DC_I_P_TOTAL,
                    36,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.DC_I_V,
                    86,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.DC_O_P_TOTAL,
                    39,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                BoolField(
                    FieldName.DC_O_SWITCH,
                    3008,
                ),
                UIntField(
                    FieldName.PV_1_I_C,
                    88,
                    unit="A",
                    sensor="current",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.PV_1_I_P,
                    87,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
            ]
        )
