from ..base_devices import BluettiDevice
from ..fields import *

# GENERATED FILE! ONLY EDIT FOR TESTING!


class EB3A(BluettiDevice):
    def __init__(self):
        super().__init__(
            [
                EnumField(
                    name=FieldName.AC_ECO_MODE,
                    address=3064,
                ),
                BoolField(
                    name=FieldName.AC_ECO_SWITCH,
                    address=3063,
                ),
                UIntField(
                    name=FieldName.AC_1_I_V,
                    address=77,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.AC_I_P_TOTAL,
                    address=37,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.AC_O_P_TOTAL,
                    address=38,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                BoolField(
                    name=FieldName.AC_O_SWITCH,
                    address=3007,
                ),
                BoolField(
                    name=FieldName.AC_POWER_LIFTING_SWITCH,
                    address=3066,
                ),
                UIntField(
                    name=FieldName.B_SOC_TOTAL,
                    address=43,
                    unit="%",
                    sensor="battery",
                    state_type="measurement",
                ),
                EnumField(
                    name=FieldName.D_CHARGING_MODE,
                    address=3065,
                ),
                StringField(
                    name=FieldName.D_INVERTER_TYPE,
                    address=10,
                ),
                EnumField(
                    name=FieldName.D_LED_MODE,
                    address=3034,
                ),
                BoolField(
                    name=FieldName.D_POWER_OFF,
                    address=3060,
                ),
                SerialNumberField(
                    name=FieldName.D_SERIAL,
                    address=17,
                ),
                VersionField(
                    name=FieldName.D_VER_ARM,
                    address=23,
                ),
                VersionField(
                    name=FieldName.D_VER_DSP,
                    address=25,
                ),
                UIntField(
                    name=FieldName.DC_I_P_TOTAL,
                    address=36,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.DC_I_V,
                    address=86,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.DC_O_P_TOTAL,
                    address=39,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                BoolField(
                    name=FieldName.DC_O_SWITCH,
                    address=3008,
                ),
            ]
        )
