from ..base_devices import BluettiDevice
from ..fields import *

# GENERATED FILE! ONLY EDIT FOR TESTING!


class EL100V2(BluettiDevice):
    def __init__(self):
        super().__init__(
            [
                UIntField(
                    FieldName.AC_1_O_V,
                    1511,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                EnumField(
                    FieldName.AC_ECO_MODE,
                    2018,
                ),
                BoolField(
                    FieldName.AC_ECO_SWITCH,
                    2017,
                ),
                UIntField(
                    FieldName.AC_1_I_C,
                    1315,
                    unit="A",
                    sensor="current",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_1_I_V,
                    1314,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_I_P_TOTAL,
                    146,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_O_P_TOTAL,
                    142,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                BoolField(
                    FieldName.AC_O_SWITCH,
                    2011,
                ),
                BoolField(
                    FieldName.AC_POWER_LIFTING_SWITCH,
                    2021,
                ),
                UIntField(
                    FieldName.B_SOC_HIGH,
                    2023,
                    unit="%",
                ),
                UIntField(
                    FieldName.B_SOC_LOW,
                    2022,
                    unit="%",
                ),
                UIntField(
                    FieldName.B_SOC_TOTAL,
                    102,
                    unit="%",
                    sensor="battery",
                    state_type="measurement",
                ),
                VersionField(
                    FieldName.B_VER_BMS,
                    6175,
                ),
                EnumField(
                    FieldName.D_CHARGING_MODE,
                    2020,
                ),
                EnumField(
                    FieldName.D_DISPLAY_MODE,
                    2067,
                ),
                SwapStringField(
                    FieldName.D_INVERTER_TYPE,
                    110,
                ),
                SerialNumberField(
                    FieldName.D_SERIAL,
                    116,
                ),
                TimeField(
                    FieldName.D_TIME_REMAINING,
                    104,
                    sensor="duration",
                ),
                EnumField(
                    FieldName.DC_ECO_MODE,
                    2015,
                ),
                BoolField(
                    FieldName.DC_ECO_SWITCH,
                    2014,
                ),
                UIntField(
                    FieldName.DC_I_P_TOTAL,
                    144,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.DC_O_P_TOTAL,
                    140,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                BoolField(
                    FieldName.DC_O_SWITCH,
                    2012,
                ),
            ]
        )
