from ..base_devices import BluettiDevice
from ..fields import *

# GENERATED FILE! ONLY EDIT FOR TESTING!


class EL30V2(BluettiDevice):
    def __init__(self):
        super().__init__(
            [
                EnumField(
                    name=FieldName.AC_ECO_MODE,
                    address=2018,
                ),
                BoolField(
                    name=FieldName.AC_ECO_SWITCH,
                    address=2017,
                ),
                UIntField(
                    name=FieldName.AC_1_I_V,
                    address=1314,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.AC_I_P_TOTAL,
                    address=146,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.AC_O_P_TOTAL,
                    address=142,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                BoolField(
                    name=FieldName.AC_O_SWITCH,
                    address=2011,
                ),
                BoolField(
                    name=FieldName.AC_POWER_LIFTING_SWITCH,
                    address=2021,
                ),
                UIntField(
                    name=FieldName.B_SOC_TOTAL,
                    address=102,
                    unit="%",
                    sensor="battery",
                    state_type="measurement",
                ),
                EnumField(
                    name=FieldName.D_CHARGING_MODE,
                    address=2020,
                ),
                SwapStringField(
                    name=FieldName.D_INVERTER_TYPE,
                    address=110,
                ),
                SerialNumberField(
                    name=FieldName.D_SERIAL,
                    address=116,
                ),
                TimeField(
                    name=FieldName.D_TIME_REMAINING,
                    address=104,
                    sensor="duration",
                ),
                EnumField(
                    name=FieldName.DC_ECO_MODE,
                    address=2015,
                ),
                BoolField(
                    name=FieldName.DC_ECO_SWITCH,
                    address=2014,
                ),
                UIntField(
                    name=FieldName.DC_I_P_TOTAL,
                    address=144,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.DC_O_P_TOTAL,
                    address=140,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                BoolField(
                    name=FieldName.DC_O_SWITCH,
                    address=2012,
                ),
            ]
        )
