from ..base_devices import BluettiDevice
from ..fields import *

# GENERATED FILE! ONLY EDIT FOR TESTING!


class EP2000(BluettiDevice):
    def __init__(self):
        super().__init__(
            [
                UIntField(
                    FieldName.AC_1_O_V,
                    1511,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_2_O_V,
                    1518,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_3_O_V,
                    1525,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_I_F,
                    1300,
                    unit="Hz",
                    sensor="frequency",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_1_I_V,
                    1314,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_2_I_V,
                    1320,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_3_I_V,
                    1326,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_O_F,
                    1500,
                    unit="Hz",
                    sensor="frequency",
                ),
                BoolField(
                    FieldName.AC_O_SWITCH,
                    2011,
                ),
                UIntField(
                    FieldName.B_SOC_HIGH,
                    2023,
                    unit="%",
                ),
                UIntField(
                    FieldName.B_SOC_LOW,
                    2022,
                    unit="%",
                ),
                UIntField(
                    FieldName.B_SOC_TOTAL,
                    102,
                    unit="%",
                    sensor="battery",
                    state_type="measurement",
                ),
                SwapStringField(
                    FieldName.D_INVERTER_TYPE,
                    110,
                ),
                SerialNumberField(
                    FieldName.D_SERIAL,
                    116,
                ),
                UIntField(
                    FieldName.G_I_F,
                    1300,
                    unit="Hz",
                    sensor="frequency",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.PV_1_I_C,
                    1214,
                    unit="A",
                    sensor="current",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.PV_1_I_P,
                    1212,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.PV_1_I_V,
                    1213,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.PV_2_I_C,
                    1222,
                    unit="A",
                    sensor="current",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.PV_2_I_P,
                    1220,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.PV_2_I_V,
                    1221,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
            ]
        )
