from ..base_devices import BluettiDevice
from ..fields import *

# GENERATED FILE! ONLY EDIT FOR TESTING!


class EP2000(BluettiDevice):
    def __init__(self):
        super().__init__(
            [
                UIntField(
                    name=FieldName.AC_1_O_V,
                    address=1511,
                    multiplier=0.1,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.AC_2_O_V,
                    address=1518,
                    multiplier=0.1,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.AC_3_O_V,
                    address=1525,
                    multiplier=0.1,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.AC_I_F,
                    address=1300,
                    multiplier=0.1,
                    unit="Hz",
                    sensor="frequency",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.AC_1_I_V,
                    address=1314,
                    multiplier=0.1,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.AC_2_I_V,
                    address=1320,
                    multiplier=0.1,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.AC_3_I_V,
                    address=1326,
                    multiplier=0.1,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.AC_O_F,
                    address=1500,
                    multiplier=0.1,
                    unit="Hz",
                    sensor="frequency",
                ),
                SwitchField(
                    name=FieldName.AC_O_SWITCH,
                    address=2011,
                ),
                UIntField(
                    name=FieldName.B_SOC_HIGH,
                    address=2023,
                    unit="%",
                ),
                UIntField(
                    name=FieldName.B_SOC_LOW,
                    address=2022,
                    unit="%",
                ),
                UIntField(
                    name=FieldName.B_SOC_TOTAL,
                    address=102,
                    unit="%",
                    sensor="battery",
                    state_type="measurement",
                ),
                SwapStringField(
                    name=FieldName.D_INVERTER_TYPE,
                    address=110,
                    size=6,
                ),
                SerialNumberField(
                    name=FieldName.D_SERIAL,
                    address=116,
                ),
                UIntField(
                    name=FieldName.G_I_F,
                    address=1300,
                    multiplier=0.1,
                    unit="Hz",
                    sensor="frequency",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.PV_1_I_C,
                    address=1214,
                    multiplier=0.1,
                    unit="A",
                    sensor="current",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.PV_1_I_P,
                    address=1212,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.PV_1_I_V,
                    address=1213,
                    multiplier=0.1,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.PV_2_I_C,
                    address=1222,
                    multiplier=0.1,
                    unit="A",
                    sensor="current",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.PV_2_I_P,
                    address=1220,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.PV_2_I_V,
                    address=1221,
                    multiplier=0.1,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
            ]
        )

    def get_iot_version(self) -> int:
        return 2
