from ..base_devices import BluettiDevice
from ..enums import *
from ..fields import *
from ..registers import *

# GENERATED FILE! ONLY EDIT FOR TESTING!


class EP500P(BluettiDevice):
    def __init__(self):
        super().__init__(
            [
                UIntField(
                    name=FieldName.AC_1_O_V,
                    address=71,
                    multiplier=0.1,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.AC_I_F,
                    address=80,
                    multiplier=0.01,
                    unit="Hz",
                    sensor="frequency",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.AC_1_I_V,
                    address=77,
                    multiplier=0.1,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.AC_I_P_TOTAL,
                    address=37,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.AC_O_F,
                    address=74,
                    multiplier=0.1,
                    unit="Hz",
                    sensor="frequency",
                ),
                SelectField(
                    name=FieldName.AC_O_MODE,
                    address=70,
                    e=OutputMode,
                ),
                UIntField(
                    name=FieldName.AC_O_P_TOTAL,
                    address=38,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                SwitchField(
                    name=FieldName.AC_O_SWITCH,
                    address=3007,
                ),
                SelectField(
                    name=FieldName.AC_UPS_MODE,
                    address=3001,
                    e=UpsMode,
                ),
                UIntField(
                    name=FieldName.B_SOC_HIGH,
                    address=3016,
                    unit="%",
                ),
                UIntField(
                    name=FieldName.B_SOC_LOW,
                    address=3015,
                    unit="%",
                ),
                UIntField(
                    name=FieldName.B_SOC_TOTAL,
                    address=43,
                    unit="%",
                    sensor="battery",
                    state_type="measurement",
                ),
                SelectField(
                    name=FieldName.D_DISPLAY_MODE,
                    address=3061,
                    e=DisplayMode,
                ),
                StringField(
                    name=FieldName.D_INVERTER_TYPE,
                    address=10,
                    size=6,
                ),
                SerialNumberField(
                    name=FieldName.D_SERIAL,
                    address=17,
                ),
                SwitchField(
                    name=FieldName.D_SPLIT_PHASE_SWITCH,
                    address=3004,
                ),
                SelectField(
                    name=FieldName.D_SPLIT_PHASE_MODE,
                    address=3005,
                    e=SplitPhaseMode,
                ),
                UIntField(
                    name=FieldName.DC_I_P_TOTAL,
                    address=36,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.DC_O_P_TOTAL,
                    address=39,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                SwitchField(
                    name=FieldName.DC_O_SWITCH,
                    address=3008,
                ),
                UIntField(
                    name=FieldName.PV_1_I_C,
                    address=88,
                    multiplier=0.1,
                    unit="A",
                    sensor="current",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.PV_1_I_P,
                    address=87,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    name=FieldName.PV_1_I_V,
                    address=86,
                    multiplier=0.1,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
            ]
        )

    def get_iot_version(self) -> int:
        return 1
