from ..base_devices import BluettiDevice
from ..fields import *

# GENERATED FILE! ONLY EDIT FOR TESTING!


class EP760(BluettiDevice):
    def __init__(self):
        super().__init__(
            [
                UIntField(
                    FieldName.AC_1_O_C,
                    1512,
                    unit="A",
                    sensor="current",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_1_O_P,
                    1510,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_1_O_V,
                    1511,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_I_F,
                    1300,
                    unit="Hz",
                    sensor="frequency",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_1_I_C,
                    1315,
                    unit="A",
                    sensor="current",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_1_I_P,
                    1313,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_1_I_V,
                    1314,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.AC_O_F,
                    1500,
                    unit="Hz",
                    sensor="frequency",
                ),
                UIntField(
                    FieldName.B_SOC_TOTAL,
                    102,
                    unit="%",
                    sensor="battery",
                    state_type="measurement",
                ),
                SwapStringField(
                    FieldName.D_INVERTER_TYPE,
                    110,
                ),
                SerialNumberField(
                    FieldName.D_SERIAL,
                    116,
                ),
                UIntField(
                    FieldName.G_I_F,
                    1300,
                    unit="Hz",
                    sensor="frequency",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.PV_1_I_C,
                    1214,
                    unit="A",
                    sensor="current",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.PV_1_I_P,
                    1212,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.PV_1_I_V,
                    1213,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.PV_2_I_C,
                    1222,
                    unit="A",
                    sensor="current",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.PV_2_I_P,
                    1220,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.PV_2_I_V,
                    1221,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.PV_3_I_C,
                    1230,
                    unit="A",
                    sensor="current",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.PV_3_I_P,
                    1228,
                    unit="W",
                    sensor="power",
                    state_type="measurement",
                ),
                UIntField(
                    FieldName.PV_3_I_V,
                    1229,
                    unit="V",
                    sensor="voltage",
                    state_type="measurement",
                ),
            ]
        )
